apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-repo-pv
  labels:
    assign-to: "redis-repo"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: <NFS SERVER>
    path: <NFS PATH>/redis
