apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-metrics-pv-1
  labels:
    assign-to: "spark-metrics"
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: <NFS SERVER>
    path: <NFS PATH>/spark-metrics
