apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-home-pv-1
  labels:
    assign-to: "user-home"
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: <NFS Server>
    path: <NFS PATH>/user-home
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-home-pv-2
  labels:
    assign-to: "user-home"
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: <NFS Server>
    path: <NFS PATH>/user-home
